import express from 'express';
import cors from 'cors';
import http from 'http';
import { Server } from 'socket.io';
import { connectDB } from './db';
import { fetchCodeforcesAccepted } from './externalSync';
import { loadContestDocuments, loadSubmissionDocuments, saveContestDocument, saveSubmissionDocument, upsertGoogleUser } from './storage';

const app = express();
const CLIENT_ORIGIN = process.env.CLIENT_ORIGIN || '*';
app.use(cors({ origin: CLIENT_ORIGIN === '*' ? '*' : CLIENT_ORIGIN.split(',').map((origin) => origin.trim()) }));
app.use(express.json({ limit: '1mb' }));

const server = http.createServer(app);
const io = new Server(server, { cors: { origin: CLIENT_ORIGIN === '*' ? '*' : CLIENT_ORIGIN.split(',').map((origin) => origin.trim()), methods: ['GET', 'POST'] } });

type McqQuestion = { id: number; question: string; options: string[]; correctIndex: number; concept: string };
type Player = { id: string; name: string; score: number };
type DuelRoom = { id: string; players: Player[]; questionIndex: number; questions: McqQuestion[]; finished: boolean };
type JudgeLanguage = 'cpp' | 'c' | 'java' | 'python' | 'javascript';
type Judge0Result = { stdout?: string | null; stderr?: string | null; compile_output?: string | null; time?: string | number | null; memory?: number | null; status?: { id?: number; description?: string } | null };
type ContestProblem = { id: string; title: string; platform: string; url: string; difficulty?: string; rating?: number; tags: string[]; stdin?: string; expectedOutput?: string; sourceCode?: string; contestCode?: string; problemIndex?: string };
type ContestMember = { id: string; name: string; handle?: string; codeforcesHandle?: string; team?: string };
type ContestSolve = { memberId: string; problemId: string; solvedAtMinute: number; attempts: number };
type StandingRow = { memberId: string; name: string; solved: number; penalty: number; score: number; solvedProblems: string[] };
type Contest = { id: string; title: string; description: string; startTime: string; durationMinutes: number; isRated: boolean; createdAt: string; members: ContestMember[]; problems: ContestProblem[]; solves: ContestSolve[]; standings: StandingRow[]; questions: McqQuestion[] };

const languageMap: Record<JudgeLanguage, number> = { cpp: 54, c: 50, java: 62, python: 71, javascript: 63 };
const waitingPlayers: Player[] = [];
const rooms = new Map<string, DuelRoom>();
const contests = new Map<string, Contest>();
const submissions: any[] = [];
const problems = [
  { id: 1, title: 'Two Sum', difficulty: 800, tags: ['array', 'hash-map'], description: 'Find two indices whose values add up to target.', stdin: '4 9\n2 7 11 15\n', expectedOutput: '0 1' },
  { id: 2, title: 'Binary Search', difficulty: 900, tags: ['binary-search'], description: 'Find the target index in a sorted array.', stdin: '5 7\n1 3 5 7 9\n', expectedOutput: '3' },
  { id: 3, title: 'Reverse Linked List', difficulty: 1200, tags: ['linked-list'], description: 'Reverse a singly linked list.', stdin: '', expectedOutput: '' }
];

function id(prefix: string) { return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`; }
function normalizeOutput(value: string | null | undefined) { return (value || '').trim().replace(/\s+/g, ' '); }
function getContestMinute(contest: Contest) { return Math.max(1, Math.floor((Date.now() - new Date(contest.startTime).getTime()) / 60000)); }
function slugHandle(name: string) { return name.trim().toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '') || `member_${Math.random().toString(36).slice(2, 6)}`; }
function uniqueByName(names: string[]) { return [...new Set(names.map((name) => String(name || '').trim()).filter(Boolean))]; }
function parseMember(input: any): ContestMember { const raw = typeof input === 'string' ? { name: input } : input || {}; const name = String(raw.name || raw.handle || raw.codeforcesHandle || '').trim(); const cf = String(raw.codeforcesHandle || raw.handle || name).trim(); return { id: id('member'), name, handle: slugHandle(name), codeforcesHandle: cf }; }
function parseCodeforcesCode(raw: string) { const clean = raw.trim().toUpperCase().replace(/\s+/g, ''); const match = clean.match(/^(\d+)([A-Z][0-9]?)$/); return match ? { contestCode: match[1], problemIndex: match[2] } : { contestCode: raw, problemIndex: '' }; }
function buildProblemUrl(platform: string, contestCode: string, problemIndex: string, url: string) { if (url?.trim()) return url.trim(); const p = platform.toLowerCase(); if (p.includes('codeforces') && contestCode && problemIndex) return `https://codeforces.com/problemset/problem/${contestCode}/${problemIndex}`; if (p.includes('leetcode') && contestCode) return `https://leetcode.com/problems/${contestCode}`; if (p.includes('atcoder') && contestCode && problemIndex) return `https://atcoder.jp/contests/${contestCode}/tasks/${contestCode}_${problemIndex.toLowerCase()}`; if (p.includes('codechef') && contestCode) return `https://www.codechef.com/problems/${contestCode}`; return ''; }
function estimateRating(index: string, supplied?: number) { if (supplied) return supplied; const first = (index || 'A').toUpperCase()[0]; return { A: 800, B: 1000, C: 1300, D: 1600, E: 1900, F: 2200 }[first as 'A'] || 1200; }
function lookupPlatformProblem(platform: string, code: string) { const p = platform.toLowerCase(); if (p.includes('codeforces')) { const parsed = parseCodeforcesCode(code); const rating = estimateRating(parsed.problemIndex); return { platform: 'Codeforces', contestCode: parsed.contestCode, problemIndex: parsed.problemIndex, sourceCode: `${parsed.contestCode}${parsed.problemIndex}`, title: `Codeforces ${parsed.contestCode}${parsed.problemIndex}`, url: buildProblemUrl('Codeforces', parsed.contestCode, parsed.problemIndex, ''), rating, difficulty: String(rating), tags: ['implementation'] }; } if (p.includes('leetcode')) return { platform: 'LeetCode', contestCode: code.trim(), problemIndex: '', sourceCode: code.trim(), title: code.trim().split('-').map((x) => x[0]?.toUpperCase() + x.slice(1)).join(' '), url: buildProblemUrl('LeetCode', code.trim(), '', ''), rating: 1200, difficulty: 'Medium', tags: ['leetcode'] }; if (p.includes('atcoder')) return { platform: 'AtCoder', contestCode: code.trim().split('_')[0], problemIndex: code.trim().split('_')[1] || 'A', sourceCode: code.trim(), title: `AtCoder ${code}`, url: buildProblemUrl('AtCoder', code.trim().split('_')[0], code.trim().split('_')[1] || 'A', ''), rating: 1000, difficulty: 'Practice', tags: ['atcoder'] }; if (p.includes('codechef')) return { platform: 'CodeChef', contestCode: code.trim(), problemIndex: '', sourceCode: code.trim(), title: `CodeChef ${code}`, url: buildProblemUrl('CodeChef', code.trim(), '', ''), rating: 1000, difficulty: 'Practice', tags: ['codechef'] }; return { platform, contestCode: code, problemIndex: '', sourceCode: code, title: `${platform} ${code}`, url: '', rating: 1000, difficulty: 'Practice', tags: [platform.toLowerCase()] }; }
function generateMcqsFromProblems(contestProblems: ContestProblem[]): McqQuestion[] { const source = contestProblems.length ? contestProblems : problems.map((p) => ({ id: String(p.id), title: p.title, platform: 'DivineCode', url: `/problems/${p.id}`, difficulty: String(p.difficulty), rating: p.difficulty, tags: p.tags })); const difficulties = ['800', '1000', '1200', '1500']; return source.flatMap((problem, index) => { const mainTag = problem.tags[0] || 'implementation'; const platformOptions = ['Codeforces', 'LeetCode', 'AtCoder', 'CodeChef'].filter((p) => p !== problem.platform).slice(0, 3); return [{ id: index * 3 + 1, question: `Which platform is selected for “${problem.title}”?`, options: [problem.platform, ...platformOptions].slice(0, 4), correctIndex: 0, concept: 'platform recognition' }, { id: index * 3 + 2, question: `Which topic best matches “${problem.title}”?`, options: [mainTag, 'graph', 'geometry', 'database'].slice(0, 4), correctIndex: 0, concept: mainTag }, { id: index * 3 + 3, question: `What rating label is attached to “${problem.title}”?`, options: [String(problem.rating || problem.difficulty || 'Practice'), ...difficulties.filter((d) => d !== problem.difficulty)].slice(0, 4), correctIndex: 0, concept: 'rating reading' }]; }).slice(0, 12).map((q, idx) => ({ ...q, id: idx + 1 })); }
function rebuildStandings(contest: Contest) { contest.standings = contest.members.map((member) => { const memberSolves = contest.solves.filter((solve) => solve.memberId === member.id); const solvedProblems = memberSolves.map((solve) => solve.problemId); const penalty = memberSolves.reduce((sum, solve) => sum + solve.solvedAtMinute + Math.max(0, solve.attempts - 1) * 20, 0); return { memberId: member.id, name: member.name, solved: memberSolves.length, penalty, score: memberSolves.length * 1000 - penalty, solvedProblems }; }).sort((a, b) => b.solved - a.solved || a.penalty - b.penalty || a.name.localeCompare(b.name)); }
function persistContest(contest: Contest) { void saveContestDocument(contest).catch((error) => console.error('Could not persist contest:', error instanceof Error ? error.message : error)); }
function recordSolve(contest: Contest, memberId: string, problemId: string) { const existing = contest.solves.find((s) => s.memberId === memberId && s.problemId === problemId); if (existing) return existing; const solve = { memberId, problemId, solvedAtMinute: getContestMinute(contest), attempts: 1 }; contest.solves.push(solve); rebuildStandings(contest); persistContest(contest); return solve; }
function serializeContestList(contest: Contest) { return { id: contest.id, title: contest.title, description: contest.description, startTime: contest.startTime, durationMinutes: contest.durationMinutes, isRated: contest.isRated, membersCount: contest.members.length, problemsCount: contest.problems.length, questionCount: contest.questions.length, createdAt: contest.createdAt }; }
async function ensureUnsolvedByContestMembers(contest: Contest, platform: string, contestCode: string, problemIndex: string) { if (!platform.toLowerCase().includes('codeforces')) return; for (const member of contest.members) { const handle = member.codeforcesHandle || member.handle || member.name; if (!handle) continue; const accepted = await fetchCodeforcesAccepted(handle, contestCode, problemIndex); if (accepted) throw new Error(`Cannot add ${contestCode}${problemIndex}. ${handle} has already solved it on Codeforces.`); } }
async function restoreFromMongo() { try { const restoredContests = await loadContestDocuments(); const restoredSubmissions = await loadSubmissionDocuments(); contests.clear(); submissions.splice(0, submissions.length, ...restoredSubmissions); for (const contest of restoredContests as Contest[]) { contest.questions = generateMcqsFromProblems(contest.problems || []); rebuildStandings(contest); contests.set(contest.id, contest); } console.log(`Mongo restore complete: ${contests.size} contest(s), ${submissions.length} submission(s).`); } catch (error) { console.error('Mongo restore failed:', error instanceof Error ? error.message : error); } }

app.get('/', (_req, res) => { res.json({ status: 'ok', app: 'DivineCode API', contests: contests.size, submissions: submissions.length }); });
app.post('/api/auth/google', async (req, res) => { try { const user = await upsertGoogleUser(req.body); res.json({ ok: true, user }); } catch (error) { res.status(400).json({ ok: false, error: error instanceof Error ? error.message : 'Could not save Google user' }); } });
app.get('/api/problems', (_req, res) => { res.json(problems.map(({ stdin, expectedOutput, ...safeProblem }) => safeProblem)); });
app.get('/api/problems/lookup', (req, res) => { const platform = String(req.query.platform || 'Codeforces'); const code = String(req.query.code || ''); if (!code.trim()) { res.status(400).json({ error: 'Problem code is required' }); return; } res.json(lookupPlatformProblem(platform, code)); });
app.get('/api/problems/:id', (req, res) => { const problem = problems.find((item) => item.id === Number(req.params.id)); if (!problem) { res.status(404).json({ error: 'Problem not found' }); return; } const { stdin, expectedOutput, ...safeProblem } = problem; res.json(safeProblem); });
app.get('/api/members/suggestions', (_req, res) => { const existing = [...contests.values()].flatMap((contest) => contest.members.map((member) => member.name)); res.json(uniqueByName([...existing, 'Rahul', 'Code Warrior', 'Team Alpha', 'Team Beta', 'Tourist', 'Petr', 'Benq', 'Errichto'])); });
app.get('/api/contests', (_req, res) => { res.json([...contests.values()].map(serializeContestList)); });
app.post('/api/contests', async (req, res) => { const { title, description, startTime, durationMinutes, isRated, members, problems: contestProblems } = req.body; if (!String(title || '').trim()) { res.status(400).json({ error: 'Contest title is required' }); return; } const safeMembers: ContestMember[] = (Array.isArray(members) ? members : []).map(parseMember).filter((m) => m.name); const tempContest: Contest = { id: id('contest'), title: String(title).trim(), description: String(description || 'Private group contest room'), startTime: startTime || new Date().toISOString(), durationMinutes: Math.max(1, Number(durationMinutes || 120)), isRated: Boolean(isRated), members: safeMembers, problems: [], solves: [], standings: [], questions: [], createdAt: new Date().toISOString() }; const safeProblems: ContestProblem[] = []; try { for (const p of Array.isArray(contestProblems) ? contestProblems : []) { const platform = String(p.platform || 'External'); const contestCode = String(p.contestCode || p.code || ''); const problemIndex = String(p.problemIndex || ''); const url = buildProblemUrl(platform, contestCode, problemIndex, String(p.url || '')); if (platform.toLowerCase().includes('codeforces')) await ensureUnsolvedByContestMembers(tempContest, platform, contestCode, problemIndex); safeProblems.push({ id: id('problem'), title: String(p.title || `${platform} ${contestCode}${problemIndex}`).trim(), platform, url, difficulty: p.difficulty ? String(p.difficulty) : problemIndex || undefined, rating: Number(p.rating || estimateRating(problemIndex)), tags: String(p.tags || platform).split(',').map((t: string) => t.trim()).filter(Boolean), stdin: String(p.stdin || ''), expectedOutput: String(p.expectedOutput || ''), sourceCode: `${contestCode}${problemIndex}`, contestCode, problemIndex }); } } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message : 'Problem already solved by participant' }); return; } if (safeMembers.length === 0) { res.status(400).json({ error: 'Add at least one contest member' }); return; } if (safeProblems.filter((p) => p.title && p.url).length === 0) { res.status(400).json({ error: 'Add at least one valid problem with a platform code or URL' }); return; } tempContest.problems = safeProblems.filter((p) => p.title && p.url); tempContest.questions = generateMcqsFromProblems(tempContest.problems); rebuildStandings(tempContest); contests.set(tempContest.id, tempContest); persistContest(tempContest); res.status(201).json(tempContest); });
app.get('/api/contests/:id', (req, res) => { const contest = contests.get(req.params.id); if (!contest) { res.status(404).json({ error: 'Contest not found' }); return; } rebuildStandings(contest); res.json(contest); });
app.get('/api/contests/:id/submissions', (req, res) => { res.json(submissions.filter((s) => s.contestId === req.params.id).slice(-100).reverse()); });
app.post('/api/contests/:id/sync/codeforces', async (req, res) => { const contest = contests.get(req.params.id); if (!contest) { res.status(404).json({ error: 'Contest not found' }); return; } const synced: any[] = []; const errors: any[] = []; for (const member of contest.members) { const handle = member.codeforcesHandle || member.handle || member.name; for (const problem of contest.problems.filter((p) => p.platform.toLowerCase().includes('codeforces'))) { const parsed = problem.contestCode && problem.problemIndex ? { contestCode: problem.contestCode, problemIndex: problem.problemIndex } : parseCodeforcesCode(problem.sourceCode || problem.title); if (!parsed.contestCode || !parsed.problemIndex) continue; try { const accepted = await fetchCodeforcesAccepted(handle, parsed.contestCode, parsed.problemIndex); if (accepted) { recordSolve(contest, member.id, problem.id); const entry = { id: id('cfsub'), contestId: contest.id, memberId: member.id, userId: handle, problemId: problem.id, platform: 'Codeforces', verdict: 'Accepted', source: 'Codeforces API', externalSubmissionId: accepted.id, language: accepted.programmingLanguage, createdAt: new Date(accepted.creationTimeSeconds * 1000).toISOString(), message: `Accepted on Codeforces as ${handle}` }; if (!submissions.some((s) => s.externalSubmissionId === entry.externalSubmissionId)) submissions.push(entry); void saveSubmissionDocument(entry).catch(() => undefined); synced.push(entry); } } catch (error) { errors.push({ handle, problem: problem.title, error: error instanceof Error ? error.message : 'Sync failed' }); } } } persistContest(contest); res.json({ ok: true, synced, errors, standings: contest.standings }); });
app.post('/api/contests/:id/extend', (req, res) => { const contest = contests.get(req.params.id); if (!contest) { res.status(404).json({ error: 'Contest not found' }); return; } contest.durationMinutes += Math.max(1, Number(req.body.minutes || 15)); persistContest(contest); res.json(contest); });
app.post('/api/contests/:id/members', (req, res) => { const contest = contests.get(req.params.id); if (!contest) { res.status(404).json({ error: 'Contest not found' }); return; } (Array.isArray(req.body.members) ? req.body.members : [req.body]).map(parseMember).forEach((member) => { if (member.name && !contest.members.some((m) => m.name.toLowerCase() === member.name.toLowerCase())) contest.members.push(member); }); rebuildStandings(contest); persistContest(contest); res.json(contest); });
app.post('/api/contests/:id/problems', async (req, res) => { const contest = contests.get(req.params.id); if (!contest) { res.status(404).json({ error: 'Contest not found' }); return; } const platform = String(req.body.platform || 'External'); const contestCode = String(req.body.contestCode || ''); const problemIndex = String(req.body.problemIndex || ''); try { await ensureUnsolvedByContestMembers(contest, platform, contestCode, problemIndex); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message : 'Problem already solved by participant' }); return; } const problem: ContestProblem = { id: id('problem'), title: String(req.body.title || 'Untitled Problem'), platform, url: buildProblemUrl(platform, contestCode, problemIndex, String(req.body.url || '')), difficulty: req.body.difficulty ? String(req.body.difficulty) : undefined, rating: Number(req.body.rating || estimateRating(problemIndex)), tags: String(req.body.tags || platform).split(',').map((t: string) => t.trim()).filter(Boolean), stdin: String(req.body.stdin || ''), expectedOutput: String(req.body.expectedOutput || ''), sourceCode: `${contestCode}${problemIndex}`, contestCode, problemIndex }; if (!problem.url) { res.status(400).json({ error: 'Problem URL is required' }); return; } contest.problems.push(problem); contest.questions = generateMcqsFromProblems(contest.problems); rebuildStandings(contest); persistContest(contest); res.json(contest); });

async function runWithJudge0(params: { sourceCode: string; language: JudgeLanguage; stdin: string; expectedOutput: string; externalOnly?: boolean }) { if (params.externalOnly) return { verdict: 'Pending Codeforces Verification', message: 'This is a Codeforces problem. Submit on Codeforces, then use Sync Codeforces. DivineCode will not mark this accepted from local code.', stdout: '', stderr: '', compile_output: '' }; const judgeUrl = process.env.JUDGE0_URL; if (!params.expectedOutput) return { verdict: 'Pending External Verification', message: 'No official local tests are configured. Standing will not update until an external platform sync or real judge accepts it.', stdout: '', stderr: '', compile_output: '' }; if (!judgeUrl) return { verdict: 'Judge Not Configured', message: 'Judge0 is not configured. Standing was not updated.', stdout: '', stderr: '', compile_output: '' }; const createResponse = await fetch(`${judgeUrl}/submissions?base64_encoded=false&wait=true`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ source_code: params.sourceCode, language_id: languageMap[params.language], stdin: params.stdin, expected_output: params.expectedOutput }) }); if (!createResponse.ok) return { verdict: 'Judge Error', message: `Judge0 request failed with status ${createResponse.status}`, stdout: '', stderr: '', compile_output: '' }; const result = (await createResponse.json()) as Judge0Result; const statusDescription = result.status?.description || 'Unknown'; let verdict = statusDescription; if (statusDescription === 'Accepted') verdict = normalizeOutput(result.stdout) === normalizeOutput(params.expectedOutput) ? 'Accepted' : 'Wrong Answer'; return { verdict, message: statusDescription, stdout: result.stdout || '', stderr: result.stderr || '', compile_output: result.compile_output || '', time: result.time || null, memory: result.memory || null }; }
app.post('/api/practice/submit', async (req, res) => { try { const { code, problemId, language = 'cpp' } = req.body; const problem = problems.find((item) => item.id === Number(problemId)); if (!problem) { res.status(404).json({ verdict: 'Rejected', message: 'Problem not found' }); return; } if (!code) { res.status(400).json({ verdict: 'Rejected', message: 'Code is required' }); return; } const result = await runWithJudge0({ sourceCode: code, language, stdin: problem.stdin, expectedOutput: problem.expectedOutput }); const saved = { id: id('practice'), problemId, language, code, verdict: result.verdict, message: result.message, source: 'Practice Judge', createdAt: new Date().toISOString() }; submissions.push(saved); void saveSubmissionDocument(saved).catch(() => undefined); res.json(result); } catch (error) { res.status(500).json({ verdict: 'Server Error', message: error instanceof Error ? error.message : 'Unknown error' }); } });
app.post('/api/submit', async (req, res) => { try { const { code, language, problemId, contestId, memberId, userId } = req.body; if (!code || !language || !problemId) { res.status(400).json({ verdict: 'Rejected', message: 'code, language and problemId are required' }); return; } if (!languageMap[language as JudgeLanguage]) { res.status(400).json({ verdict: 'Rejected', message: 'Unsupported language' }); return; } let stdin = ''; let expectedOutput = ''; let contest: Contest | undefined; let externalOnly = false; if (contestId) { contest = contests.get(String(contestId)); if (!contest) { res.status(404).json({ verdict: 'Rejected', message: 'Contest not found' }); return; } const contestProblem = contest.problems.find((item) => item.id === String(problemId)); if (!contestProblem) { res.status(404).json({ verdict: 'Rejected', message: 'Contest problem not found' }); return; } stdin = contestProblem.stdin || ''; expectedOutput = contestProblem.expectedOutput || ''; externalOnly = contestProblem.platform.toLowerCase().includes('codeforces'); } else { const problem = problems.find((item) => item.id === Number(problemId)); if (!problem) { res.status(404).json({ verdict: 'Rejected', message: 'Problem not found' }); return; } stdin = problem.stdin; expectedOutput = problem.expectedOutput; } const result = await runWithJudge0({ sourceCode: code, language: language as JudgeLanguage, stdin, expectedOutput, externalOnly }); if (result.verdict === 'Accepted' && contest && memberId) recordSolve(contest, String(memberId), String(problemId)); const saved = { id: id('sub'), userId, memberId, contestId, problemId, language, code, verdict: result.verdict, message: result.message, source: externalOnly ? 'Pending Codeforces' : 'DivineCode Judge', stdout: result.stdout, stderr: result.stderr, compileOutput: result.compile_output, time: result.time ? String(result.time) : undefined, memory: typeof result.memory === 'number' ? result.memory : undefined, createdAt: new Date().toISOString() }; submissions.push(saved); void saveSubmissionDocument(saved).catch((error) => console.error('Could not save submission:', error instanceof Error ? error.message : error)); res.json({ ...result, language, problemId, contestId: contest?.id, standings: contest?.standings || null }); } catch (error) { res.status(500).json({ verdict: 'Server Error', message: error instanceof Error ? error.message : 'Unknown error' }); } });
function publicQuestion(room: DuelRoom) { const q = room.questions[room.questionIndex]; return { id: q.id, question: q.question, options: q.options, concept: q.concept, number: room.questionIndex + 1, total: room.questions.length }; }
function emitRoom(room: DuelRoom) { io.to(room.id).emit('duel:state', { roomId: room.id, players: room.players, question: room.finished ? null : publicQuestion(room), finished: room.finished, winner: room.finished ? [...room.players].sort((a, b) => b.score - a.score)[0] : null }); }
io.on('connection', (socket) => { socket.on('duel:join', (payload: { name?: string }) => { const player: Player = { id: socket.id, name: payload?.name || `Player-${socket.id.slice(0, 4)}`, score: 0 }; if (waitingPlayers.length === 0) { waitingPlayers.push(player); socket.emit('duel:waiting', { message: 'Waiting for another player...' }); return; } const opponent = waitingPlayers.shift()!; const roomId = `room-${Date.now()}`; const seedContest = [...contests.values()].at(-1); const room: DuelRoom = { id: roomId, players: [opponent, player], questionIndex: 0, questions: seedContest?.questions?.length ? seedContest.questions : generateMcqsFromProblems([]), finished: false }; rooms.set(roomId, room); socket.join(roomId); io.sockets.sockets.get(opponent.id)?.join(roomId); io.to(roomId).emit('duel:start', { roomId, players: room.players }); emitRoom(room); }); socket.on('duel:answer', (payload: { roomId: string; questionId: number; answerIndex: number }) => { const room = rooms.get(payload.roomId); if (!room || room.finished) return; const current = room.questions[room.questionIndex]; const player = room.players.find((item) => item.id === socket.id); if (!player || current.id !== payload.questionId) return; const correct = current.correctIndex === payload.answerIndex; player.score += correct ? 10 : -3; io.to(room.id).emit('duel:feedback', { playerId: socket.id, playerName: player.name, correct, correctIndex: current.correctIndex, concept: current.concept }); room.questionIndex += 1; if (room.questionIndex >= room.questions.length) room.finished = true; setTimeout(() => emitRoom(room), 700); }); socket.on('disconnect', () => { const waitingIndex = waitingPlayers.findIndex((p) => p.id === socket.id); if (waitingIndex >= 0) waitingPlayers.splice(waitingIndex, 1); }); });

void connectDB().then(() => restoreFromMongo()).catch((error) => console.error('Initial MongoDB connection failed:', error instanceof Error ? error.message : error));
const PORT = Number(process.env.PORT) || 4000;
server.listen(PORT, () => console.log(`DivineCode API and duel socket server running on port ${PORT}`));
